name: autotag

on:
  push:
    branches:
      - "master"

jobs:
  tag-release:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Auto Tag
        uses: Klemensas/action-autotag@stable
        with:
          GITHUB_TOKEN: "${{ secrets.REPOSNAPSHOT_API_KEY }}"
          tag_prefix: "v"
